name: Daily USD Exchange Rate Scraper

on:
  schedule:
    # Run at 10:30 AM Sri Lanka Time (UTC+5:30 = 05:00 UTC) - 30 minutes after AUD
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual triggering for testing

env:
  TZ: Asia/Colombo

jobs:
  scrape-usd-exchange-rates:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip
    
    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Display current time (Sri Lanka)
      run: |
        echo "Current UTC time: $(date -u)"
        echo "Current Sri Lanka time: $(TZ=Asia/Colombo date)"
    
    - name: Run USD exchange rate scraper
      env:
        MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
      run: |
        echo "🚀 Starting USD exchange rate scraper..."
        python daily_usd_rate_scraper.py
    
    - name: Upload USD logs and screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: usd-scraper-logs-${{ github.run_number }}
        path: |
          logs/
          screenshots/
          usd_execution_summary.json
        retention-days: 7

    - name: Upload USD logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: usd-scraper-failure-logs-${{ github.run_number }}
        path: |
          logs/
          screenshots/
          usd_execution_summary.json
        retention-days: 14